# -*- coding: utf-8 -*-
"""googe_news_scrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J2z9qaXgqboh4qhrVpCTmxCs02Mu35Ha
"""

#!pip install pygooglenews --upgrade

from pygooglenews import GoogleNews
import pandas as pd

gn = GoogleNews()

def get_titles(search):
  stories = []
  search = gn.search(search, when = '6m')
  newsitem = search['entries']
  for item in newsitem:
    story = {
        'title' : item.title,
        'link' : item.link,
        'date' : item.published
    }
    stories.append(story)
  return stories

df = pd.DataFrame.from_dict(data)

df

data_AAPL = get_titles('AAPL')
df_AAPL = pd.DataFrame.from_dict(data_AAPL)
df_AAPL["Stock"] = "AAPL"
df_AAPL

data_AMZN = get_titles('AMZN')
df_AMZN = pd.DataFrame.from_dict(data_AMZN)
df_AMZN["Stock"] = "AMZN"
df_AMZN

data_NVIDIA = get_titles('NVIDIA')
df_NVIDIA = pd.DataFrame.from_dict(data_NVIDIA)
df_NVIDIA["Stock"] = "NVIDIA"
df_NVIDIA

data_CRM = get_titles('CRM')
df_CRM = pd.DataFrame.from_dict(data_CRM)
df_CRM["Stock"] = "CRM"
df_CRM

data_ORCL = get_titles('ORCL')
df_ORCL = pd.DataFrame.from_dict(data_ORCL)
df_ORCL["Stock"] = "ORCL"
df_ORCL

data_MSFT = get_titles('MSFT')
df_MSFT = pd.DataFrame.from_dict(data_MSFT)
df_MSFT["Stock"] = "MSFT"
df_MSFT

data_V = get_titles('VISA STOCK')
df_V = pd.DataFrame.from_dict(data_V)
df_V["Stock"] = "V"
df_V

data_BAC = get_titles('BAC')
df_BAC = pd.DataFrame.from_dict(data_BAC)
df_BAC["Stock"] = "BAC"
df_BAC

data_ADBE = get_titles('ADBE')
df_ADBE = pd.DataFrame.from_dict(data_ADBE)
df_ADBE["Stock"] = "ADBE"
df_ADBE

data_MA = get_titles('MASTERCARD STOCK')
df_MA = pd.DataFrame.from_dict(data_MA)
df_MA["Stock"] = "MA"
df_MA

frames = [df_AAPL, df_ADBE, df_AMZN, df_BAC, df_CRM, df_MA, df_MSFT, df_NVIDIA, df_ORCL, df_V]

result = pd.concat(frames)
result.reset_index(drop=True,inplace=True)

result

result.to_csv("google_news.csv")